package triage

import (
	"context"
	"path/filepath"
	"strconv"
	"strings"
)

// DriverFileName is the generated agent brief in a run.
const DriverFileName = "DRIVER.md"

// RenderDriver renders DRIVER.md: a self-contained brief any agentic CLI can
// execute against this run.
//
// Pure over (run, profile), like the other documents. The brief is generated
// rather than shipped static because it names *this* run's id in every
// command — an agent that has to substitute a placeholder is an agent that
// will eventually substitute the wrong one.
//
// It encodes the field trial's coordinator/worker topology as instructions
// rather than as camp orchestration. Camp never calls a model; the routing
// tiers below are advice the agent follows by convention.
func RenderDriver(runID string, profile ResolvedProfile, batches int) []byte {
	var b strings.Builder

	b.WriteString("# Triage driver brief — " + runID + "\n\n")
	b.WriteString("> Generated by `camp triage start` for this run.\n" +
		"> **Do not edit.** Re-running start replaces it.\n\n")
	b.WriteString("You are judging a campaign's workitems. Camp owns every mutation; " +
		"you supply evidence and proposals as data. Nothing you do here moves a " +
		"workitem.\n\n")

	writeDriverLoop(&b, runID)
	writeDriverSchema(&b)
	writeDriverRouting(&b, profile, batches)
	writeDriverRules(&b)
	writeDriverCompletion(&b, runID)

	return []byte(b.String())
}

// writeDriverLoop states the loop with this run's own commands.
func writeDriverLoop(b *strings.Builder, runID string) {
	b.WriteString("## The loop\n\n")
	b.WriteString("Repeat until the queue is empty:\n\n")
	b.WriteString("```\n")
	b.WriteString("camp triage queue --run " + runID + " --json\n")
	b.WriteString("#   -> rows awaiting judgment, each with its policy and routing tier\n\n")
	// No --json: template emits the record as its whole output and has no such
	// flag. The brief must name flags that exist, which is exactly what the
	// scripted-driver test checks by running these lines rather than
	// paraphrasing them.
	b.WriteString("camp triage evidence template <stable-id> --run " + runID + "\n")
	b.WriteString("#   -> a record pre-filled with every fact camp already holds\n\n")
	b.WriteString("camp triage evidence set <stable-id> --run " + runID + " --file <record.json>\n")
	b.WriteString("#   -> submit what you read. Judgment fields are yours; signals are camp's\n\n")
	b.WriteString("camp triage propose <stable-id> --run " + runID +
		" --disposition <label> --file <rationale.json>\n")
	b.WriteString("#   -> propose one disposition from that row's own vocabulary\n")
	b.WriteString("```\n\n")
	b.WriteString("A row you cannot decide is left alone. Recording a low-confidence " +
		"guess is worse than leaving the row for a human, because the guess looks " +
		"like a judgment.\n\n")
	b.WriteString("If you read nothing — the row is obvious from its metadata — say so " +
		"honestly:\n\n```\ncamp triage evidence set <stable-id> --run " + runID +
		" --no-evidence\n```\n\n")
}

// writeDriverSchema shows the evidence record with a filled example.
func writeDriverSchema(b *strings.Builder) {
	b.WriteString("## The evidence record\n\n")
	b.WriteString("```json\n")
	b.WriteString(`{
  "schema_version": "` + SchemaVersion + `",
  "stable_id": "design-observation-boundary",
  "original_goal": "Decide where obey's observation boundary sits",
  "delivered": ["the disk-first watcher", "the mtime/pid liveness rule"],
  "missing": ["the remote-machine case"],
  "stale_assumptions": ["assumed hooks; the design moved to file-watching"],
  "related": ["WI-a1b2c3", "festival:CI0009", "pr:obey#239"],
  "open_decisions": ["whether remote observation is in scope at all"],
  "confidence": "high",
  "confidence_notes": "high for implementation state; medium for the remote question",
  "anchors": [
    {"kind": "path", "path": "workflow/design/x/README.md", "hash": "sha256:..."},
    {"kind": "pr", "repo": "Obedience-Corp/obey", "number": 239, "observed": "merged"}
  ],
  "produced_by": {"role": "evidence", "runtime": "<your tool>", "at": "..."}
}
`)
	b.WriteString("```\n\n")
	b.WriteString("**Anchors are the part that expires.** Each one is a fact camp can " +
		"re-check mechanically, so a verdict that rested on a PR being open goes " +
		"stale by itself when the PR merges. A record with no anchors is valid and " +
		"supports a verdict that never expires — which is usually not what you want.\n\n")
	b.WriteString("`camp triage evidence template` pre-fills the deterministic fields " +
		"(age, stages, latest run status, referencing commits, path hashes). Those " +
		"are facts camp measured. Everything else is your reading, and mixing the " +
		"two would make the record claim someone concluded what camp merely " +
		"observed.\n\n")
}

// writeDriverRouting renders the profile's advisory tiers as prose.
func writeDriverRouting(b *strings.Builder, profile ResolvedProfile, batches int) {
	b.WriteString("## How to work\n\n")
	b.WriteString("Use a " + string(profile.Routing.EvidenceTier) +
		" model or pass for per-item document reads. ")
	b.WriteString("Escalate to a " + string(profile.Routing.EscalationTier) +
		" pass for rows where the code contradicts the workitem, or where the " +
		"evidence disagrees with itself. ")
	b.WriteString("Synthesize each batch with a " + string(profile.Routing.SynthesisTier) +
		" pass. ")
	b.WriteString("Run at most " + strconv.Itoa(profile.Routing.MaxConcurrent) +
		" workers concurrently.\n\n")

	b.WriteString("Work batch by batch: this run has " + strconv.Itoa(batches) +
		" batch(es) of up to " + strconv.Itoa(profile.Review.BatchSize) +
		" rows. Finish a batch before starting the next, so a human reviewing " +
		"early batches is reading a settled set rather than a moving one.\n\n")

	b.WriteString("How hard to look is per lane, and the queue tells you which " +
		"applies to each row:\n\n")
	b.WriteString("| Attention stage | Evidence depth |\n| --- | --- |\n")
	for _, stage := range sortedKeys(profile.Evidence.DepthByStage) {
		b.WriteString("| " + stage + " | " + string(profile.Evidence.DepthByStage[stage]) + " |\n")
	}
	b.WriteString("\n`deep` means read the workitem against the code, the PRs, and the " +
		"festivals it names. `metadata` means the marker and registry signals only. " +
		"`none` means decide from the review card without reading.\n\n")
}

// writeDriverRules states the advisory boundary verbatim.
func writeDriverRules(b *strings.Builder) {
	b.WriteString("## Rules\n\n")
	b.WriteString("- **Read-only.** You do not move, rename, promote, or retire anything.\n")
	b.WriteString("- **No lifecycle mutations.** Not `camp workitem promote`, not " +
		"`camp workitem stage`, not `camp dungeon move`, not `camp workitem split`.\n")
	b.WriteString("- **Do not edit workitems.** Not their markers, not their documents.\n")
	b.WriteString("- **Submit only through `camp triage evidence set` and " +
		"`camp triage propose`.** They are the only two write paths you have.\n")
	b.WriteString("- **A proposal is advisory.** Terminal dispositions — retiring or " +
		"splitting a workitem — always require a human's recorded approval, and " +
		"nothing you submit bypasses that.\n")
	b.WriteString("- **Rationale is required.** A proposal without reasoning is " +
		"refused, because a verdict nobody can audit is worse than no verdict.\n\n")
}

// writeDriverCompletion states how to know the job is done.
func writeDriverCompletion(b *strings.Builder, runID string) {
	b.WriteString("## When you are finished\n\n")
	b.WriteString("```\ncamp triage queue --run " + runID + " --json\n```\n\n")
	b.WriteString("An empty queue means every row is judged. Report what you left " +
		"undecided and why — those are the rows a human most needs to see.\n\n")
	b.WriteString("Then stop. Approving is a human's act:\n\n")
	b.WriteString("```\ncamp triage review\n```\n")
}

// WriteDriver renders and writes the run's DRIVER.md, returning its path.
func WriteDriver(ctx context.Context, run *Run, profile ResolvedProfile) (string, error) {
	if err := ctx.Err(); err != nil {
		return "", err
	}
	path := filepath.Join(run.Dir, DriverFileName)
	body := RenderDriver(run.ID, profile, BatchCount(run.Manifest))
	if err := writeAtomic(path, body); err != nil {
		return "", err
	}
	return path, nil
}
