package triage

import (
	"context"
	"path/filepath"
	"strconv"
	"strings"

	camperrors "github.com/Obedience-Corp/camp/internal/errors"
)

// WorkflowDocFileName is the companion step guide written into a run.
const WorkflowDocFileName = "WORKFLOW.md"

// ScaffoldWorkflowDoc writes the run's companion WORKFLOW.md and returns its
// path.
//
// The document is generated from run data and subordinate to it: it exists so
// step guidance shows up in the familiar fest shape, and deleting it loses
// nothing. This is the header and phase list only; the driver brief that tells
// an agent exactly what to run for this run is generated by a later sequence.
func ScaffoldWorkflowDoc(ctx context.Context, run *Run) (string, error) {
	if err := ctx.Err(); err != nil {
		return "", err
	}
	if run == nil || run.Manifest == nil {
		return "", camperrors.NewValidation("run", "is required", nil)
	}

	path := filepath.Join(run.Dir, WorkflowDocFileName)
	body := renderWorkflowDoc(run)
	if err := writeAtomic(path, []byte(body)); err != nil {
		return "", err
	}
	return path, nil
}

// renderWorkflowDoc builds the document. Pure and deterministic: the same run
// data always renders the same bytes, so the file can be regenerated at any
// time without churning a diff.
func renderWorkflowDoc(run *Run) string {
	var b strings.Builder
	b.WriteString("# Triage run ")
	b.WriteString(run.ID)
	b.WriteString("\n\n")
	b.WriteString("Generated from this run's data. It is a reading aid, not state:\n")
	b.WriteString("delete it and nothing is lost.\n\n")

	b.WriteString("- Profile: `")
	b.WriteString(run.Manifest.Profile.Name)
	b.WriteString("`\n- Mode: `")
	b.WriteString(string(run.Manifest.Mode))
	b.WriteString("`\n- Rows: ")
	b.WriteString(strconv.Itoa(len(run.Manifest.Rows)))
	b.WriteString(" in ")
	b.WriteString(strconv.Itoa(BatchCount(run.Manifest)))
	b.WriteString(" batch(es)\n\n")

	b.WriteString("## Phases\n\n")
	b.WriteString("Camp owns this order. A profile changes what happens inside a\n")
	b.WriteString("phase, never the sequence or its safety gates.\n\n")
	for _, phase := range workflowPhases {
		b.WriteString("- **")
		b.WriteString(phase.name)
		b.WriteString("** — ")
		b.WriteString(phase.who)
		b.WriteString(": ")
		b.WriteString(phase.what)
		b.WriteString("\n")
	}
	b.WriteString("\n## Current phase\n\n`")
	b.WriteString(string(run.State.Phase))
	b.WriteString("`\n\nRun `camp triage status` for where the run actually stands;\n")
	b.WriteString("this line is only accurate as of generation.\n")
	return b.String()
}

// workflowPhases is the phase list the document renders, with who acts.
var workflowPhases = []struct{ name, who, what string }{
	{"created", "camp", "the run exists and holds the active slot"},
	{"snapshotted", "camp", "the inventory is frozen with its resolved profile"},
	{"judging", "agents or you", "evidence and proposals are submitted per row"},
	{"reviewing", "you", "verdicts are recorded lane by lane"},
	{"applying", "camp", "approved verdicts execute, each with a receipt"},
	{"verified", "camp", "discovery re-run and every applied row checked"},
}
